name: IOT CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set Debug Environment Variable
      run: echo "DEBUG=false" >> $GITHUB_ENV  # Устанавливаем DEBUG в false для производственной среды
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          fuser -k 8080/tcp
          cd server_iot/iot88/
          python3 -m venv envV1
          git pull
          source envV1/bin/activate.bat
          pip install -r requirements.txt
          gunicorn --bind 0.0.0.0:5000 wsgi:app
          pwd